### ISSUE TITLE
problem loading stored file

### ISSUE THREAD

**Issue by lfrank** [flatironinstitute/kachery-cloud#7] opened 2022-07-03 02:26 UTC
Using the access groups option I stored a series of files and saved the encrypted uri's. Loading those uris using kcl.load_file doesn't work for me, nor does loading them after decryption.

This is for access group
`aqidbrogrt`

The encrypted uri is: 
`sha1-enc://bf03a31646b25c56bdaedc8fa9d4137dac9c783bf2787b8fcf571e19d3aee48f9a6b48f1304240031d339264ee00c7a8.ag_aqidbrogrt`
When I decrypt using kcl.decrypt I get
`sha1://89d8ba74d54d3be6f0e24a182e4f8e21d4e25524`

I've added both @magland and Jeff's google ids to the access group to facilitate testing

**Comment by magland** [comment] 2022-07-04 15:31
Strange.

* Could you just do a simple test with one of the files? Try to store without encrypting and then see if you can load.
* If that works, try encrypting the uri, and then see if that loads.
* If either of those don't work, try this simpler test:

```python
import kachery_cloud as kcl
uri = kcl.store_text('random-h887001')
uri2 = kcl.encrypt_uri(uri, access_group='aqidbrogrt')
txt1 = kcl.load_text(uri2)
print(txt1)
```

Also, it doesn't seem like I'm in the access group. Could you double check that for jmagland [at] flatironinstitute [dot] org?

**Comment by lfrank** [comment] 2022-07-04 23:34
I’ve added you (again, I believe) to the access group:
[cid:64126BCF-63F9-48FB-883C-8653C96E2B0D]
so hopefully that will help.

Separately, the text saves and retrieves work both locally on the UCSF machine and on my laptop.

The file saving and retrieval works when I link a file on the UCSF machine and load based on that link on the same machine.

The file retrieval does that work when I use that same (unencrypted) uri on my laptop at home.

For reference, that uri is

 'sha1://9004ce7af2db4e5861fad7e0143d6be656501d33'

thoughts?


On Jul 4, 2022, at 8:31 AM, Jeremy Magland ***@***.******@***.***>> wrote:

This Message Is From an External Sender
This message came from outside your organization.


Strange.

  *   Could you just do a simple test with one of the files? Try to store without encrypting and then see if you can load.
  *   If that works, try encrypting the uri, and then see if that loads.
  *   If either of those don't work, try this simpler test:

import kachery_cloud as kcl
uri = kcl.store_text('random-h887001')
uri2 = kcl.encrypt_uri(uri, access_group='aqidbrogrt')
txt1 = kcl.load_text(uri2)
print(txt1)

Also, it doesn't seem like I'm in the access group. Could you double check that for jmagland [at] flatironinstitute [dot] org?

**Comment by magland** [comment] 2022-07-05 13:41
I think the issue is that you are using `link_file(...)` which only stores the file locally, rather than `store_file(...)` which uploads immediately to the cloud. This is related to our slack discussion. I'll close this issue for now, but feel free to reopen if appropriate.

**Closed by magland** 2022-07-05 13:41 UTC
